language: node_js
cache:
  directories:
    - node_modules
    - typings
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
install:
  - npm install
  - npm run typings:install
before_script:
  - npm prune
  - npm run compile
script:
  - npm run coverage:test
  - npm run coverage:check
  - npm run coverage:report
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
